GameCMS Storage: Getting the server address from cvars
ChatAdditions/ChatAdditions_AMXX pull request #275
Opened 2022-05-10 15:50 UTC by ma4ts

To close this issue: https://github.com/ChatAdditions/ChatAdditions_AMXX/issues/274#issue-1231351898

2022-05-11 11:00 UTC, wopox1337 requested changes

2022-05-11 11:00 UTC, wopox1337 commented on cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
> +  )
Нет нужды разделять на два квара. Сделать единым.

2022-05-11 11:00 UTC, wopox1337 commented on cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
> +  if (!strcmp(ca_server_ip, "127.0.0.1") || ca_server_ip[0] == EOS) {
недопонимание в виде `127.0.0.1`, который интерпретируется далее как `net_address` недопустимо.


Изначальное значение для CVar'a должно быть `""`, и только в этом случае должно браться значение из `net_address`

2022-05-11 11:00 UTC, wopox1337 commented on cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
> +  if (!strcmp(ca_server_ip, "127.0.0.1") || ca_server_ip[0] == EOS) {
Желательно инвертировать условие.

```pawn
if(cvar[0] != EOS)
  return
  
// some code
```

2022-05-11 19:54 UTC, Nord1cWarr1or commented on cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
> +  if (!strcmp(ca_server_ip, "127.0.0.1") || ca_server_ip[0] == EOS) {
Я бы ещё в описание квара добавил пометку, мол, оставить пустым для авто-определения

2022-05-15 10:36 UTC, wopox1337 requested changes

2022-05-15 10:36 UTC, wopox1337 commented on cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
> +new ca_server_address[MAX_IP_LENGTH + MAX_PORT_LENGTH],
Задать фиксированную длину в 128, убрать константу для длины порта.

2022-05-15 10:36 UTC, wopox1337 commented on cstrike/addons/amxmodx/scripting/CA_Storage_GameCMS.sma
> +  new serverAddress[2][MAX_IP_LENGTH + MAX_PORT_LENGTH]
Так же задать длину в 128

2022-05-15 12:28 UTC, wopox1337 approved these changes

2022-05-15 12:33 UTC, merged